# Generated by Django 2.1.3 on 2018-12-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.TextField()),
                ('department', models.TextField()),
                ('profession', models.TextField()),
                ('division', models.TextField()),
            ],
        ),
    ]
